version: 1.0.{build}
image: Visual Studio 2017

artifacts:
  - path: 'CHANGELOG.md'

# gem install github_changelog_generator が毎回実行されないようにキャッシュする
cache:
  - C:/Ruby25/lib/ruby/gems/2.5.0/
  - C:/Ruby25/bin

build_script:
  - set PATH=C:\Ruby25\bin;%PATH%
  - ruby --version
  - where ruby
#  - dir C:\Ruby25\bin
#  - dir C:\Ruby25\lib\ruby\gems\2.5.0\
  - gem install github_changelog_generator
  - mkdir c:\tmp
  - github_changelog_generator -u sakura-editor -p sakura --exclude-labels duplicate,question,invalid,wontfix,CI,management,refactoring
